### PR TITLE
Replace touch device checks

### LINKED ISSUE #1389: util.browser.touchDevice causes unwanted side-effects on touchscreen laptops & 2-in-1's
**Describe the bug**
Many laptops and 2-in-1's are now touch screen enabled devices; `util.browser.touchDevice` causes unwanted side-effects on these devices, even in desktop mode, which include: 
- About page opening in a new tab
https://github.com/nasa-gibs/worldview/blob/master/web/js/ui/info.js#L86-L88
- Notifications expanding to full window width/height 
https://github.com/nasa-gibs/worldview/blob/master/web/js/notifications/ui.js#L435-L440
- Possibly the reason why swipe mode does not work in some browsers on my 2-in-1 computer
https://github.com/nasa-gibs/worldview/blob/master/web/js/notifications/ui.js#L435-L440
https://github.com/nasa-gibs/worldview/blob/master/web/js/date/compare-picks.js#L26

**To Reproduce**
1. Use a 2-in-1 device to view worldview
2. Click info button -> About
3. Device opens in a new window

1. Use a 2-in-1 device to view worldview
2. Click notifications button
3. Device opens in a new window

**Expected behavior**
These devices should behave as desktop devices.

**Screenshots**
The notification issue was initally reported here and includes a screenshot:
https://github.com/nasa-gibs/worldview/issues/1181

**Desktop (please complete the following information):**
- Device Dell 7390 2-in-1 
 - OS: Windows 10
 - Browser: Chrome, Firefox

**Additional context**
It would seem we can remove the touchDevice conditional in all of these instances except the comparison. The important thing to check is that the browser size is small; the comparison issues may need separate testing.

### PR DESCRIPTION
**Pull request by ZachTRice**
## Description

Fixes #1389 .

Adds new tests for mobile and mobile + tablet devices. Replaces touchDevice checks for mobile/tablet checks.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/map/compare/compare.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ export function mapCompare(models, config) {
   self.spy = Spy;
   self.active = false;
   self.dragging = false;
-  self.EventTypeObject = util.browser.touchDevice ? TOUCH_EVENT : MOUSE_EVENT;
+  self.EventTypeObject = util.browser.mobileAndTabletDevice ? TOUCH_EVENT : MOUSE_EVENT;
```
Comment (Benjaki2) [inline web/js/map/compare/compare.js]: @ZachTRice I am thinking we might want to just use both events here and with the `compare-picks.js` for touch screen computers

**Comment by ZachTRice** [comment]
@Benjaki2 please review my latest changes. Thanks!
