### PR TITLE
hide layers without snapshot #3343

### LINKED ISSUE #3343: Trying to Download image with HLS grid active returns an error
**Describe the bug**
Trying to Download image with HLS grid active returns an error

**To Reproduce**
1. Go to '?v=-242.16209711079125,-39.60457890548289,4.255336084090402,79.70252833303897&as=2016-09-21-T00%3A00%3A00Z&ae=2016-09-28-T00%3A00%3A00Z&l=HLS_MGRS_Granule_Grid,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=false&al=true&ab=on&t=2016-09-26-T00%3A00%3A00Z'
2. Try to download image
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OSX
 - Browser: Chrome

**Additional context**
I don't believe there is a WMS layer for the HLS grid. Should we force the user to disable this layer, similarly to graticules?

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #3343

Ability to disable layers that don't work with WVS

- [x] Add hide layer capability 
- [x] Add snapshot to layer schema and docs

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/modules/image-download/util.js [hunk 1]
```diff
@@ -287,3 +289,53 @@ export function getPercentageFromPixel(maxDimension, dimension) {
...
+ *
+ * @return {String}
+ */
+export function getNonDownloadableLayerWarning(nonDownloadableLayer) {
+  const layerStr = getNamesOfNondownloadableLayers(nonDownloadableLayer);
+  if (!layerStr) return '';
+  const multiLayers = layerStr.indexOf(',') > -1;
+  return multiLayers ? `The ${layerStr} layers cannot be used to take a snapshot. Would you `
+  + 'like to temporarily hide these layers?' : `The ${layerStr} layer cannot be used to take a snapshot. Would you `
+  + 'like to temporarily hide this layer?';
```
Comment (jasontk19) [inline web/js/modules/image-download/util.js:331]:
```suggestion
  const layerPluralStr = multiLayers ? 'layers' : 'layer';
  return `The ${layerStr} ${layerPluralStr} cannot be included in a snapshot. Would you like to temporarily hide this layer?`;
```

Comment (jasontk19) [reply web/js/modules/image-download/util.js:331]: Suggested a tweak to the verbiage here to "cannot be included in a snapshot" rather than "cannot be used to take a snapshot"

File: web/js/modules/image-download/util.js [hunk 2]
```diff
@@ -287,3 +289,53 @@ export function getPercentageFromPixel(maxDimension, dimension) {
...
 }
+
+/**
+ * Find if there are layers that cannot be downloaded
+ * @param {Array} visibleLayers
+ *
+ * @return {Bool}
+ */
+export function hasNonDownloadableVisibleLayer(visibleLayers) {
+  const notDownloadable = !!lodashFind(visibleLayers, { snapshot: false });
```
Comment (jasontk19) [inline web/js/modules/image-download/util.js:300]: Not really a big deal either way but, why use lodash when we can do this natively with ES6?  I don't think we need to phase out lodash entirely since it does have some handy methods that don't exist natively and the file size savings would only be around 25kb gzipped but, I've been trying to replace things like this when I see them since I've got a slight preference for the native approach.  For example, using the spread operator in a reducer instead of lodash assign just looks cleaner to me.

Doing a find would be just a simple one liner in ES6 as well but, I think `Array.some()` is even more appropriate here since it returns a boolean:
```
export function hasNonDownloadableVisibleLayer(visibleLayers) {
  return visibleLayers.some(({ snapshot = true }) => !snapshot);
}
```

File: doc/config/layers.md [hunk 3]
```diff
@@ -105,6 +105,7 @@ Example:
 * **track**: Classify a layer's track direction. This will usually be either ascending or descending and will be displayed within the title of the layer in the Measurement / Sources add modal view if provided.
 * **description**: Point to a markdown file within the metadata folder to provide a layer description.
 * **wrapX**: Wrap the layer across the anti-meridian.
+* **snapshot**: Ability to be downloaded via worldview snapshots (WVS). Default is `true`.
```
Comment (jasontk19) [inline doc/config/layers.md:108]: I think adding a new property to configs where the default value is considered `true` is a bit awkward in JavaScript since an `undefined` value is considered `false`.  It might be preferable to to name the property something like `disableSnapshot` so the default value can be `false`.  This allows a check for matching layers to look like:
```
visibleLayers.filter(({ disableSnapshot }) => !disableSnapshot);
```
instead of the following which hurts my head a little bit to look at:
```
visibleLayers.filter(({ snapshot = true }) => !snapshot);
```

File: web/js/modules/image-download/util.js [hunk 4]
```diff
@@ -287,3 +289,53 @@ export function getPercentageFromPixel(maxDimension, dimension) {
...
+  + 'like to temporarily hide this layer?';
+}
+/**
+ * Get array of layers that will be removed if nofication is accepted
+ * @param {Array} visibleLayers
+ *
+ * @return {Array}
+ */
+export function getNonDownloadableLayers(visibleLayers) {
+  return lodashFilter(visibleLayers, { snapshot: false });
```
Comment (jasontk19) [inline web/js/modules/image-download/util.js:340]: Same here with ES6 v lodash.  Could be:
```
export function getNonDownloadableLayers(visibleLayers) {
  return visibleLayers.filter(({ snapshot = true }) => !snapshot);
}
```

**Review by jasontk19 — CHANGES_REQUESTED** [review]
Functionality looks good!  Just a few minor worth considering.

**Review by edplato — APPROVED** [review]
Works great 👍🏽 @jasontk19 hit on some good changes related to the ES6 refactor vs `lodash` where reasonable

**Review by jasontk19 — APPROVED** [review]
💯
