### PR TITLE
Fix running data tooltip in compare mode

### LINKED ISSUE #2437: No way to tell when hovering over a value for single classification palette
**Describe the bug**
If a layer has a single color classification palette, we are currently always showing the label next to the colorbox.  With this behavior, there is no way to tell if you are hovering the mouse over a point on the map that matches this value for this layer.

**To Reproduce**
1. Go to https://worldview.sit.earthdata.nasa.gov/?v=46.94546382826535,-17.16228931699522,51.69595210951535,-11.282406504495222&l=MODIS_Combined_Thermal_Anomalies_All,Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor

**Expected behavior**
Label should only show on hover so user can tell if they are hovering over a pixel that matches.

**Screenshots**
Screen Shot 2019-11-21 at 3 22 55 PM

### LINKED ISSUE #2438: Running-data tooltip offset problem in compare mode
**Describe the bug**
Running data tooltips for classification layers in compare mode B have an offset problem
**To Reproduce**
1. Go to `?l=NDH_Landslide_Hazard_Distribution_2000,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&l1=NDH_Landslide_Hazard_Distribution_2000,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&ca=false`
2. Hover over the right side of the map'
3. See error

**Screenshots**
Screen Shot 2019-11-21 at 2 47 41 PM

**Desktop (please complete the following information):**
 - OSX
 - CHROME

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #2438 
Fixes #2437 

* Only show tooltip for a palette item in compare mode if user is hovering over the active side of the A/B divide
* Show tooltip for single item palettes when running data for that item is active (more easily distinguish if & what you are pointing at in certain situations)

A good set of layers to test with:
http://localhost:3000/?v=-23.84371974109054,10.409624626741433,18.16799900890946,57.44868712674143&t=2017-01-16-T00%3A00%3A00Z&t1=2017-01-09-T00%3A00%3A00Z&l=AIRS_CO_Total_Column_Day,GRanD_Dams,Last_of_the_Wild_1995-2004,VIIRS_SNPP_Thermal_Anomalies_375m_Night,VIIRS_SNPP_Thermal_Anomalies_375m_Day,MODIS_Terra_CorrectedReflectance_TrueColor,Coastlines&l1=AIRS_CO_Total_Column_Day,GRanD_Dams,Last_of_the_Wild_1995-2004,VIIRS_SNPP_Thermal_Anomalies_375m_Night,VIIRS_SNPP_Thermal_Anomalies_375m_Day,MODIS_Terra_CorrectedReflectance_TrueColor,Coastlines&ca=true

### CODE REVIEW

File: web/js/containers/sidebar/layer.js [hunk 1]
```diff
@@ -54,11 +56,14 @@ class Layer extends React.Component {
       isMobile
     } = this.props;
     if (!lodashIsEmpty(renderedPalette)) {
-      const isRunningData = !!runningObject;
+      const isRunningData = compare.active
+        ? (runningObject || {}).layerGroupName === layerGroupName
```
Comment (Benjaki2) [inline web/js/containers/sidebar/layer.js]: My only thought is that don't you need to pass `layerGroupName` in the runningObject. `compare.active ? compare.activeString === layerGroupName` here should do the trick?

Comment (jasontk19) [reply web/js/containers/sidebar/layer.js]: Yep, good catch!
