### PR TITLE
Revert map change:resolution zoom event

### LINKED ISSUE #3187: Dateline is missing at certain zoom levels
**Describe the bug**
Dateline is missing at certain zoom levels.

**To Reproduce**
1. Go to default page and drag map towards a dateline
2. Hover over dateline and note the dateline and dates are visible
3. Zoom in one level
4. Hover over dateline and note the dateline isn't shown however dates are visible

**Expected behavior**
Date line is visible on hover throughout zoom levels.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #3187  .

- [x] Revert map `change:resolution` zoom event to remove debounce causing event fire issue used in dateline, revise dateline to prevent unnecessary updates

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/components/dateline/dateline.js [hunk 1]
```diff
@@ -115,9 +127,9 @@ class Line extends React.Component {
         />
         <line
           className="dateline-hidden"
-          onMouseOver={this.mouseOverHidden.bind(this)}
-          onMouseMove={this.mouseOverHidden.bind(this)}
-          onMouseOut={this.mouseOutHidden.bind(this)}
+          onMouseOver={this.mouseOverHidden}
+          onMouseMove={this.mouseOverHidden}
```
Comment (Benjaki2) [inline web/js/components/dateline/dateline.js:131]: 👍

File: web/js/map/ui.js [hunk 2]
```diff
@@ -971,7 +956,10 @@ export default function mapui(models, config, store, ui) {
         $zoomOut.button('enable');
       }
     };
-    map.getView().on('change:resolution', lodashDebounce(debouncedZoomChange, 30));
+    map.getView().on('change:resolution', () => {
```
Comment (Benjaki2) [inline web/js/map/ui.js:959]: I think the denounce leading option https://lodash.com/docs/#debounce might have been another way to solve. Just FYI for future reference.  `shouldComponentUpdate` seems like a good solution.

**Review by Benjaki2 — APPROVED** [review]
Nice! I honestly wasn't able to reproduce the bug though (Maybe since I don't use a mouse).
