### PR TITLE
Only show gif creation button tooltip on button hover

### LINKED ISSUE #2210: Only show "too many frames" tooltip on GIF button on hover
**Describe the bug**
The "too many frames were selected" tooltip in the animation widget shows above the product picker dialog content.  

**To Reproduce**
1. Open animation widget
2. Select a large date range (>40 frames)
3. Open product picker

**Expected behavior**
We should only show the tooltip on mouse hover.

**Screenshots**

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #2210.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/animation-widget.js [hunk 1]
```diff
@@ -525,6 +531,7 @@ function mapStateToProps(state) {
     timeScaleFromNumberKey[useInterval],
     customSelected && customDelta ? customDelta : delta
   );
+  console.log(numberOfFrames);
```
Comment (edplato) [inline web/js/containers/animation-widget.js]:
```suggestion
```
