### PR TITLE
Adjust toolbar modal responsive positions

### LINKED ISSUE #1844: Share link modal offset in mobile (SIT v3.0)
**Describe the bug**
Can only see half of share link modal in mobile view

**To Reproduce**
1. Go to home
2. Click on share button

**Screenshots**
image

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 12
 - Browser safari

### LINKED ISSUE #1858: Links in toolbar modal are underlined (SIT v3.0)
**Describe the bug**
Links are underlined in the toolbar list modals.

**Expected behavior**
Links are not underlined in list modals.

**Screenshots**
Screenshot at Jul 16 15-55-38

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.5
 - Browser: Chrome
 - Version 75

### PR DESCRIPTION
**Pull request by ZachTRice**
## Description

Fixes #1844, Fixes #1858 

- Removes position right from modal method
- Adds classes for toolbar modals
- Adjusts each toolbar modal responsive positioning
- Removes underline from toolbar list modals

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/toolbar.js [hunk 1]
```diff
@@ -30,17 +30,15 @@ const CUSTOM_MODAL_PROPS = {
   TOOLBAR_PROJECTION: {
     headerText: null,
     type: 'toolbar',
-    modalClassName: 'toolbar-list-modal toolbar-modal',
+    modalClassName: 'toolbar-list-modal toolbar-projeciton-modal toolbar-modal',
```
Comment (Benjaki2) [inline web/js/containers/toolbar.js]: misspelling of `projection`

Comment (ZachTRice) [reply web/js/containers/toolbar.js]: Good catch. Updated the spelling in `toolbar.js` and `toolbar.css`
