### PR TITLE
Fix missing token replacement bug with dist build and webpack

### LINKED ISSUE #1190: Tokens not substituted in tour components [tour.walk.5]
**Describe the bug**

Text in the tour says NAME instead of Worldview

**To Reproduce**

- Start tour.
- Go to step "Toolbar"
- NAME is found in the text

**Expected behavior**
"Worldview" should be in place of NAME

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [IE11]
 - Version [11]

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #1190  .

- fixes token replacement dist build bug
- remove copying of index.html in webpack build which is unused
- prevent remove comments from html

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: tasks/dist.js [hunk 1]
```diff
@@ -16,7 +16,12 @@ let brand = require('../build/worldview/brand/brand.json');
...
   'build/worldview/index.html',
   'build/worldview/build/wv.js',
-  'build/worldview/pages/about.html'
+  'build/worldview/build/wv.css.map',
+  'build/worldview/pages/about.html',
+  'build/worldview/pages/tour.html',
+  'build/worldview/pages/unsupported_browser.html',
+  'build/worldview/pages/curl.html',
+  'build/worldview/pages/wget.html'
 ];
```
Comment (mike-mcgann) [inline tasks/dist.js]: `build/worldview/pages/*.html` might be better at this point just in case others get added later.

Comment (edplato) [reply tasks/dist.js]: Good call, I pushed up your recommended change.
