### PR TITLE
Make mobile send feedback via email 

### LINKED ISSUE #1867: Feedback module does not open in mobile (UAT V3.0)
**Describe the bug**
Feedback module does not open in mobile.

**To Reproduce**
1. From a mobile device, click 'Send Feedback' in info drop down menu
2. Note no feedback modal/email triggered and no error shown

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: Android
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #1867
- [x] Open feedback in mobile with mail client

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/info.js [hunk 1]
```diff
@@ -47,16 +47,23 @@ class InfoList extends Component {
...
+      isMobile
     } = this.props;
+    const feedbackAction = isMobile
+      ? { href: 'mailto:@MAIL@?subject=Feedback for @LONG_NAME@ tool' }
+      : {
+        onClick: () => {
+          sendFeedback(feedbackIsInitiated);
+        }
+      };
+    console.log(feedbackAction);
```
Comment (edplato) [inline web/js/containers/info.js]:
```suggestion
```
