### PR TITLE
Fix console warning

### LINKED ISSUE #3293: Console warning when adding layers in product picker
**Describe the bug**
``` 
Warning: Cannot update a component from inside the function body of a different component.
    in Draggable (created by ConnectFunction)
    in ConnectFunction (created by PrivateDraggable)
    in PrivateDraggable (created by PublicDraggable)
    in PublicDraggable (created by LayerRow)
    in LayerRow (created by ConnectFunction)
...
```

**To Reproduce**
1. Open product picker
2. Add any layer
3. See warning in console

**Additional context**

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #3293

* Only happened on layer with palettes
* Update to not call `dispatch` outside of a `useEffect`

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/sidebar/layer-row.js [hunk 1]
```diff
@@ -96,11 +96,13 @@ function LayerRow (props) {
...
         />
       );
-    } if (!isLoading) {
-      requestPalette(layer.id);
     }
   };
 
+  useEffect(() => {
+    if (!isLoading && layer && hasPalette) requestPalette(layer.id);
+  }, [layer]);
```
Comment (Benjaki2) [inline web/js/containers/sidebar/layer-row.js:104]: Not positive, but maybe you want to use `[layer.id])`. Uncertain how that object would be compared in this case.

**Review by Benjaki2 — APPROVED** [review]
👍 Looks like Travis is breaking, but that is probably unrelated.

File: web/js/containers/sidebar/layer-row.js (hunk 1 above)
Comment (jasontk19) [reply web/js/containers/sidebar/layer-row.js:104]: I _think_ it's an object reference comparison and since the `layer` prop shouldn't be changing on this component I think it will have the same effect if we use `layer.id`

Comment (jasontk19) [reply web/js/containers/sidebar/layer-row.js:104]: Actually, after some debugging on this it looks like this runs fewer times when we check for `layer.id` instead of `layer` so that seems like the better approach.  Also it looks like a few other places in the app are throwing this warning so I want to see if I can track those down and fix them in the same PR.
