### PR TITLE
Inactive events alert

### LINKED ISSUE #3186: Permalinks with closed EONET events should show an alert
**Describe the bug**
If you load the app with a closed event ID in the permalink, the alert that is supposed to inform the user that this event is unavailable does not show.  Instead, trying to load any _other_ event will cause the alert to incorrectly show.

**To Reproduce**
1. Go to https://worldview.earthdata.nasa.gov/?e=EONET_5133
2. No alert shows
3. Cick any event in the list
4. The alert incorrectly states that the selected event is no longer active

**Expected behavior**
The alert should show only for the event included in the permalink.

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #3186.

- [x] make sure alert shows only when event is not available
- [x] replace old alert type with new one

## To Test:

1. Go to [http://localhost:3000/?e=EONET_5133](http://localhost:3000/?e=EONET_5133)
2. Confirm alert shows
3. Close alert
4. Click various other events, confirm they load properly 
5. Confirm alert does not show when clicking other events

### CODE REVIEW

**Review by minniewong — CHANGES_REQUESTED** [review]
If you go to the inactive link and leave the inactive event alert box up and click on other events, the event ID updates to that event in the inactive alert box (even though the event is definitely active).

Screen Shot 2020-11-12 at 10 34 52 AM

File: web/js/map/natural-events/ui.js [hunk 1]
```diff
@@ -314,7 +309,7 @@ export default function naturalEventsUI(ui, config, store, models) {
       self.markers = naturalEventMarkers.draw();
       naturalEventsTrack.update(null);
     }
-    store.dispatch(deselectEventAction);
+    // store.dispatch(deselectEventAction);
```
Comment (Benjaki2) [inline web/js/map/natural-events/ui.js:312]: This dispatch does seem weird and looks like it could cause some sort of never ending dispatch loop but removing it seems to also introduce an error where an event can be active in the "map" state but not in the "Global" state.

to reproduce:
1. Click on event in middle of map.
2. change to polar proj.
3. return to geo proj.
4. see error : Event is selected in list but not on map

**Review by Benjaki2 — CHANGES_REQUESTED** [review]

File: web/js/map/natural-events/ui.js (hunk 1 above)
Comment (jasontk19) [reply web/js/map/natural-events/ui.js:312]: Hmmm, yeah this seemed like either a) it wasn't doing anything since `deselectEvent` what is being called when a deselect event action is dispatched or b) was causing an infinite loop of dispatching.

With this line still commented out, I wasn't able to reproduce this specific error with the few events I tried.  Is there a specific event that is breaking this for you?

**Review by minniewong — APPROVED** [review]
Working great now!

File: web/js/map/natural-events/ui.js (hunk 1 above)
Comment (Benjaki2) [reply web/js/map/natural-events/ui.js:314]: I'm not seeing the error anymore. 🤯

**Review by Benjaki2 — APPROVED** [review]
🎉
