### PR TITLE
Fix console error thrown when switching projections

### LINKED ISSUE #723: Console error when switching projections
When switching projections the following console error occurs:
`Cannot read property '0' of null`

The issue is that during loading the `coords` variable used in the `onMouseMove` function does not have a default value set.

screenshot_2

### PR DESCRIPTION
**Pull request by ZachTRice**
Fixes #723

Changes in this pull request:

- Set the coords variable to [0,0] by default so that it is not null.

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/map/ui.js [hunk 1]
```diff
@@ -853,7 +853,7 @@ export function mapui(models, config) {
         return;
       }
       pixels = map.getEventPixel(e.originalEvent);
-      coords = map.getCoordinateFromPixel(pixels);
+      coords = map.getCoordinateFromPixel(pixels) || [0, 0];
```
Comment (localjo) [inline web/js/map/ui.js]: I don't fully understand this code, but I think it might be better to add a line after this like;
```
if (!coords) return;
```
Rather than setting a coordinate of `[0,0]`.

Comment (ZachTRice) [reply web/js/map/ui.js]: Good eye, thanks
