### PR TITLE
Animation start/end date updates

### LINKED ISSUE #1869: Animation widget should select the timeline date as the start date and end date should be 7 days forward (UAT v3.0)
**Describe the bug**
Animation widget should select the timeline date as the start date and end date should be 7 days forward/in the future; not 7 days previous to the start date. 

**To Reproduce**
1. Go to UAT
2.Change the date to 2019 JUL 1
3. Open animation widget
4. See error - Start date is 2019 JUN 24; End date is 2019 JUL 1

**Expected behavior**
In production, it sets the start date as 2019 JUL 1 and end date as 2019 JUL 8

**Screenshots**
UAT
uat-animationdates

PROD
prod-animationdates

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
UAT v3.0

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #1869

- [x] start and end dates are refreshed when tour date changes
- [x] startdate should be active date and end date should be 7 days later unless 7 days later is past today's date

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/modules/animation/actions.js [hunk 1]
```diff
@@ -10,12 +10,29 @@ import {
...
 export function onActivate() {
   return (dispatch, getState) => {
-    const { compare, date } = getState();
+    const { compare, date, animation } = getState();
     const dateStr = compare.isCompareA ? 'selected' : 'selectedB';
-    dispatch({ type: OPEN_ANIMATION, date: date[dateStr] });
+    const activeDate = date[dateStr];
+    if (!animation.startDate || !animation.endDate) {
+      const sevenDaysBefore = util.dateAdd(activeDate, 'day', -7);
+      const severDaysAfter = util.dateAdd(activeDate, 'day', 7);
```
Comment (edplato) [inline web/js/modules/animation/actions.js]: change `severDaysAfter` to `severDaysAfter` in a few places

Comment (Benjaki2) [reply web/js/modules/animation/actions.js]: good catch
