### PR TITLE
Fix animation widget interactions on touch devices

### LINKED ISSUE #3337: Animation panel buttons unresponsive to touch event (iPad)
**Describe the bug**
Almost every single button inside the animation panel (FPS slider excluded) is totally unresponsive to touch events.  Play, loop, create gif, date up/down arrows, minimize,  and close are all unresponsive

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS
 - Browser: Safari

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #3337.

The `react-draggable` component was causing all the child elements in this widget to be drag targets of touch events which prevented the primary touch interaction with them.

## To test

1. Load the app in Chrome, set device to iPad
2. Confirm all buttons in the animation widget respond as expected to touch events both in collapsed and expanded mode

### CODE REVIEW

File: web/js/containers/animation-widget.js [hunk 1]
```diff
@@ -457,10 +459,13 @@ class AnimationWidget extends React.Component {
       hasSubdailyLayers,
     } = this.props;
     const { speed, widgetPosition } = this.state;
+    const cancelSelector = '.no-drag, .interval-btn-container, .date-arrows';
```
Comment (edplato) [inline web/js/containers/animation-widget.js:462]: You may be able to remove `.interval-btn-container,` from this string since `.no-drag` is added to that element already.

**Review by edplato — APPROVED** [review]
Looks good 👍🏽

File: web/js/containers/animation-widget.js (hunk 1 above)
Comment (jasontk19) [reply web/js/containers/animation-widget.js:462]: Nice, good catch!
