### PR TITLE
Stop animation on projection switch

### LINKED ISSUE #3347: Animation does not stop playing when you change the projection
**Describe the bug**
date.animation.14 on the timeline test [page](https://wiki.earthdata.nasa.gov/display/WOR/S-06+%5Bdate%5D%3A+Timeline) has an Expected Result of 
"The animation should stop
Pause button should reset to the play button"

this does not happen.  If I start the animation and switch to any projection, it continues to play.
Mac/Chrome Version 88.0.4324.150

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #3347 

Also, removes some lodash dependency where ES6 will suffice

### CODE REVIEW

File: web/js/containers/projection.js [hunk 1]
```diff
@@ -94,6 +95,7 @@ const mapDispatchToProps = (dispatch) => ({
   updateProjection: (id, config) => {
     dispatch(changeProjection(id));
     dispatch(resetProductPickerState(id));
+    dispatch(stop());
```
Comment (Benjaki2) [inline web/js/containers/projection.js:98]: Nit pick... But I would lean towards only firing the dispatcher only if animating.

**Review by Benjaki2 — APPROVED** [review]

File: web/js/containers/projection.js (hunk 1 above)
Comment (jasontk19) [reply web/js/containers/projection.js:98]: Good call!
