### PR TITLE
Selected date / coverage facet issue fix

### LINKED ISSUE #2973: Coverage facet does not account for compare mode
**Describe the bug**
When using compare mode, if adding a layer to list B the coverage facet is set for the date of list A.

**To Reproduce**
1. Enable compare mode
2. Select list B
3. Set the date in list B to 2017 Jun 13
4. Add layers, go to facets
5. Notice the "available at date" facet is set for the list A date/time

**Expected behavior**
Facet considers list B date/time when that list is active

**Screenshots**
Screen Shot 2020-06-25 at 9 16 42 AM

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #2973 

- [x] Makes sure "Available on ..." filter for coverage facet reflects the appropriate date when in compare mode
- [x] Fixes an issue where, if the "Available on..." filter was checked, and the date was changed, things would get into a weird state
- [x] Introduce a simple `getSelectedDate` Redux selector to use throughout the app when needing to reference the current selected date so we don't have to check compare mode state all over the app
- [x] Update product picker E2E tests to confirm bug fix

### Date Changed
1. Go to `http://localhost:3000/?t=2020-06-01`
2. Open product picker
3. Click filter button
4. Enable "Available 2020 Jun 01" filter
5. Close product picker
6. Change date to 2015 Jun 01
7. Open product picker
8. Confirm coverage filter date has changed to "Available 2015 Jun 01" and is still enabled

---

### Comparison Mode
1. Go to `http://localhost:3000/?t=2020-06-01`
2. Open product picker
3. Click filter button
4. Enable "Available 2020 Jun 01" filter
5. Close product picker
6. Enable comparison mode
7. Select "B" tab in sidebar
8. Open product picker
9. Confirm coverage filter date has changed to "Available 2020 May 25" and is still enabled

---
@edplato -> code review
@Benjaki2  -> testing

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/modules/date/selectors.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export default function getSelectedDate ({ date, compare }) {
+  return date[
+    compare.isCompareA ? 'selected' : 'selectedB'
+  ];
+}
```
Comment (Benjaki2) [inline web/js/modules/date/selectors.js:5]: Good call
