### PR TITLE
Animations layer caching 

### LINKED ISSUE #2166: Looped animations over 10 steps do not use cached layer tiles
**Describe the bug**
Looping animations with more than 10 steps enabled causes layer tiles to be re-requested on each play through.  

**To Reproduce**
1. Open animation tool
2. Set interval to 1 day, select 11 total days of range
3. Play

**Expected behavior**
We should be caching these layer tiles so they are only loaded once.

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #2166.

This change prevents the removal of a layer form the cache prior to adding it during animation.  Presumably this was implemented intentionally to refresh this item in the cache so that it was not automatically removed but, in my testing I had a hard time reproducing a scenario where this was an issue.  Looped animations performed significantly better with this change and I was able to see animations of up to ~90 days play smoothly without re-requesting layer tiles each time.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/modules/map/selectors.js [hunk 1]
```diff
@@ -5,40 +5,22 @@ import { promiseLayerGroup } from './util';
...
-    key = mapUi.layerKey(
-      def,
-      {
-        date: date
-      },
-      state
-    );
-    layer = cache.getItem(key);
-    if (layer) {
-      cache.removeItem(key);
```
Comment (Benjaki2) [inline web/js/modules/map/selectors.js]: It's a rare case and I could be wrong but I think you actually want to recreate the layer even if it is in the cache:

e.g: If you were to look at a layer at some time before starting an animation it would be stored in our  `cachai cache` and the `tileCache`. But at some point it might be popped from the `tileCache`. Removing it here means `createLayer()` will actually recreate the layer (instead of skipping it's creation) `shifting` it to the top of the tileCache.

Comment (jasontk19) [reply web/js/modules/map/selectors.js]: Yeah, conceptually this makes sense to me... I just had a hard time finding a scenario where I could see this causing any problems.  From what I can tell, I _think_ that if the item exists in the `cachai` cache but has been cleared from the tile cache, OL just re-requests the tiles.  I haven't dug into their code to confirm this but, I saw instances in really long animations where an item existed in the `cachai` cache yet tile requests were still being made. I assumed this was an indicator that that they were purged from the `tileCache`.

Comment (jasontk19) [reply web/js/modules/map/selectors.js]: ... and if OL just re-requests the tiles when they've been purged from the `tileCache` then I'm guessing that's essentially not that different from recreating the layer to force it to the top of the cache.  

Let me know what you think.

Comment (Benjaki2) [reply web/js/modules/map/selectors.js]: Thats seems about right. The only difference is that the re-request won't go out until you role over that date.
