### PR TITLE
Scroll to selected event in sidebar on click

### LINKED ISSUE #1948: Clicking on an event on the map does not move that listing in the Event list
**Describe the bug**
If I click on an event on the map, I expect to be able to see the event listing in the event list. But if this event is not near the top of the list, you have to manually scroll to that highlighted listing to find it. 

**To Reproduce**
1. Click on Events tab
2. Click on an event on the map that is not at the top of the event list
3. See that you are zoomed to the event, but don't know what the event is called because the event list does not scroll to that event, unless you manually scroll down the list to find the highlighted event. 

**Expected behavior**
You would expect to be able to easily see the event listing when you click on an event on the map. Either the event listing should appear at the top of the list, or the list should scroll to that spot where the event is listed. 

**Screenshots**
Clicked on random event on map. The event listing does not show up on the event list on the left. You have to manually scroll to the highlighted event to find it.

Screen Shot 2019-08-02 at 10 24 48 AM

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #1948  .

- Set vertical `scrollTop` of scrollbar to bring selected/highlighted event into view in the sidebar

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [ ] I have added necessary documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/sidebar/events.js [hunk 1]
```diff
@@ -93,6 +103,15 @@ class Events extends React.Component {
       : hasRequestError
         ? 'There has been an ERROR retrieving events from the EONET events API'
         : '';
+
+    let scrollBarVerticalTop = 0;
+    if (events && selected.id) {
```
Comment (Benjaki2) [inline web/js/containers/sidebar/events.js]: Looks like it doesn't get the right index in polar projections

```suggestion
    if (visibleEvents && selected.id) {
      var index = Object.keys(visibleEvents).indexOf(selected.id);
      // 12 === li total top/bottom padding
      // 32.2 === li height (varies slightly, Chrome 100% browser zoom height used)
      scrollBarVerticalTop = index ? index * (12 + 32.2) : 0;
    }
```

Comment (edplato) [reply web/js/containers/sidebar/events.js]: Good fix, I'll get that pushed up.
