### PR TITLE
Fix granule labels incorrectly positioned in OpenLayers 4.4.x+

### LINKED ISSUE #528: Large "+" buttons in Data Download on initial load [dd.sel.1]
When zoomed out, the data download buttons do no scale properly. 
[Issue Example](https://worldview.earthdata.nasa.gov/?p=geographic&l=MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,MODIS_Terra_Aerosol,Coastlines&t=2013-09-28&z=3&v=-347.0625,-226.40625,347.0625,226.40625&ab=off&as=2013-09-28&ae=2013-10-05&av=3&al=true&download=MOD04_L2)
Internal Test `dd.sel.1`. 
Affects IE11, Chrome, FF. Edge works as expected.

### PR DESCRIPTION
**Pull request by ZachTRice**
Connects to #701, Connects to #683, Fixes #528

Changes in this pull request:

- Upgrade OpenLayers to 4.5.0
- Move hover labels from buttonStyle function to hoverStyle & set exceedLength attribute to true
- Arrange function calls so hover styles are called last resulting in labels overlaying buttons rather than appearing being them

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/data/map.js [hunk 1]
```diff
@@ -47,37 +47,30 @@ export function dataMap(model, maps, config) {
...
+    return [new OlStyleStyle({
+      image: new OlStyleIcon({
+        src: image,
+        scale: dim.scale
+      })
+    })];
   };
 
   var hoverStyle = function (feature) {
+    var dim = getButtonDimensions();
```
Comment (localjo) [inline web/js/data/map.js]: Since you're creating this variable in a new place, it might be a good time to take the opportunity and rename all of the `dim` variables in this file to `dimensions` so it's easier to read in the future. Your call.

**Comment by localjo** [comment]
Looks good. Let's merge into `develop`! :)
