### PR TITLE
Don't update permalink before user interacts with page

### LINKED ISSUE #1314: Permalink updates before anything happens
**Describe the bug**
Permalink updates with feature states before anything happens
**To Reproduce**
Load page

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description
Depends on #2462
Fixes #1314

Don't update permalink before user does anything
- [x] Prevent layer state mutations

## Further comments
The `def.previousDate = someDate && def.nextDate = someDate` Code was mutating the redux state in the layer builder, causing the layer flag (`l`) in the permalink to update when a non-related action was fired. This PR attaches the previous and next date Info to the OL tileLayer object instead of our layers state object.

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/map/layerbuilder.js [hunk 1]
```diff
@@ -140,29 +143,40 @@ export function mapLayerBuilder(models, config, cache, ui, store) {
...
-      // if current date is outside previous and next dates avaiable, recheck range
-      if (dateTime <= previousDateTime || dateTime >= nextDateTime) {
-        dateRange = datesinDateRanges(def, date);
-        previousDateFromRange = prevDateInDateRange(def, date, dateRange);
+    let previousLayerDate = previousLayer.previousDate;
+    let nextLayerDate = previousLayer.nextDate;
+    if (!state.animation.isPlaying) {
+      // need to get previous available date to prevent unecessary requests
+      let dateRange;
+      // let previousDateFromRange;
```
Comment (edplato) [inline web/js/map/layerbuilder.js]: this was left over from my PR
```suggestion
```

File: web/js/map/layerbuilder.js [hunk 2]
```diff
@@ -140,29 +143,40 @@ export function mapLayerBuilder(models, config, cache, ui, store) {
...
+        const nextDateTime = previousLayer.nextDate.getTime();
+        // if current date is outside previous and next dates avaiable, recheck range
+        if (dateTime <= previousDateTime || dateTime >= nextDateTime) {
+          dateRange = datesinDateRanges(def, date);
+          const { next, previous } = prevDateInDateRange(def, date, dateRange);
+          previousDateFromRange = previous;
+          previousLayerDate = previous;
+          nextLayerDate = next;
+        } else {
+          previousDateFromRange = def.previousDate;
```
Comment (edplato) [inline web/js/map/layerbuilder.js]:
```suggestion
          previousDateFromRange = previousLayer.previousDate;
```
