### PR TITLE
Revise how slider handles speed state

### LINKED ISSUE #2608: Animation widget speed slider is jumpy with retaining state
**Describe the bug**
Animation widget speed slider is jumpy with retaining state and requires a subsequent event (hover over timeline, click outside of browser window, etc.) to update. Props/state update related.

**To Reproduce**
1. Go to main app page, open animation widget
2. Drag slider handle from `3` to `7.5` and release
3. Note jump back to `3`, click out of browser window and it updates to `7.5`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #2608  .

- [x] Remove `getDerivedStateFromProps` which was causing some delayed update issues

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/animation-widget.js [hunk 1]
```diff
@@ -139,12 +139,6 @@ class AnimationWidget extends React.Component {
     }
   }
 
-  static getDerivedStateFromProps(props, state) {
```
Comment (Benjaki2) [inline web/js/containers/animation-widget.js]: Though a rare case, I think this would be needed if there are two consecutive tour steps with animations. 

Adding a location `key` to the animation widget could be a good replacement for `getDerivedStateFromProps`... similar to https://github.com/nasa-gibs/worldview/blob/master/web/js/app.js#L119

Comment (edplato) [reply web/js/containers/animation-widget.js]: Thanks, that change fixes tour related issues.
