### PR TITLE
Fix vector dialog

### LINKED ISSUE #2477: Multi-tab vector dialog can break app
**Describe the bug**
When you click from a two tab dialog with the second tab selected to a one tab dialog, the app breaks
`/?v=-83.94922083883691,32.74951652483711,-78.78468817629832,34.8462491492915&t=2019-12-02-T00%3A07%3A29Z&l=GRanD_Reservoirs,GRanD_Dams,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor`
**Screenshots**
Screen Shot 2019-12-02 at 5 50 31 PM

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #2477
When you click from a two tab dialog with the second tab selected to a one tab dialog, the app breaks

- [x] rerender vector-dialog container component on every change to dialog

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/containers/map-interactions.js [hunk 1]
```diff
@@ -104,7 +105,8 @@ const mapDispatchToProps = dispatch => ({
         CompletelyCustomModal: vectorDialog,
         isResizable: true,
         dragHandle: '.modal-header',
-        dialogKey: new Date().getUTCMilliseconds(),
+        dialogKey,
```
Comment (jasontk19) [inline web/js/containers/map-interactions.js]: Looks like we are passing `dialogKey` twice as both `dialogKey` and `key`.  Probably just need one of these?

Comment (Benjaki2) [reply web/js/containers/map-interactions.js]: Ahh didn't see this comment until already merged. `dialogKey` is something being used by the child. But the `key` is not really a prop and isn't accessible to the child. Changing the key causes a the parent react-component to re-render (I didn't learn this until semi-recently, super useful)

Comment (jasontk19) [reply web/js/containers/map-interactions.js]: Ah right, it's _that_ `key
