### PR TITLE
Check for loop reset on start date and set timeout on animation date queuing

### LINKED ISSUE #3029: Animation precache not consistent for geostationary layers
**Describe the bug**
Animation precache not consistent for geostationary layers. When running a custom 10 minute animation with geostationary imagery, the tiles do not consistently load before the map animates to the next step. This issue appears to be most prevalent when selecting an animation range with loop on, starting the animation from halfway through the selected range, and when the loop resets back to the start of the range there is no imagery as it continues to step through the animation.

**To Reproduce**
1. Go to '?v=-306.30431975790134,-116.42781891278513,19.383180242098632,95.63468108721487&t=2020-07-24-T06%3A40%3A00Z&z=4&ics=true&ici=5&icd=10&as=2020-07-24-T00%3A00%3A00Z&ae=2020-07-26-T00%3A00%3A00Z&l=GOES-West_ABI_Air_Mass,GOES-West_ABI_Band13_Clean_Infrared,GOES-West_ABI_Band2_Red_Visible_1km,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&al=true&ab=on'
2. Start animation and let run though till it loops from the start of the range
3. Note missing imagery still in process of loading as the animation steps through

**Expected behavior**
Larger range of precaching and/or pause while animation catches up with precaching.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #3029 .

- [x] Add check for start date to fix animation hanging on loop reset
- [x] Add animation speed dependent timeout for adding dates to prevent rapid stream of dates that can cause the animation to run sluggishly trying to catch up with requests

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/components/animation-widget/play-queue.js [hunk 1]
```diff
@@ -358,9 +364,9 @@ class PlayAnimation extends React.Component {
     this.addToInQueue(date);
     this.queue
       .add(() => promiseImageryForTime(date, activeLayers))
-      .then((date) => {
+      .then((addedDate) => {
```
Comment (Benjaki2) [inline web/js/components/animation-widget/play-queue.js:367]: 👍

File: web/js/components/animation-widget/play-queue.js [hunk 2]
```diff
@@ -305,8 +309,10 @@ class PlayAnimation extends React.Component {
       && nextDate <= endDate
       && nextDate >= startDate
     ) {
-      this.addDate(nextDate);
-      this.checkQueue();
+      setTimeout(() => {
+        this.addDate(nextDate);
+        this.checkQueue();
+      }, Math.floor(1000 / speed));
```
Comment (Benjaki2) [inline web/js/components/animation-widget/play-queue.js:315]: I like that... Should make the Queue easier to maintain.
