### PR TITLE
Prevent track and point removal beyond min/max zoom with mousewheel

### LINKED ISSUE #1045: Natural events track clusters/points disappear on max zoom in/out
### Description

With a natural events iceberg that has a track selected, if you keep zooming in or out all the way the points/clusters will eventually disappear.

### Steps to Reproduce

1. Pick an iceberg from natural events that has multiple data points
2. Keep zooming in or out all the way and the points clusters/points will disappear

**Expected behavior:**   
Clusters/points should remain visible/clickable

**Actual behavior:**   
Clusters/points disappear

### Environment

Version: 2.5.1 
Browser: [all]

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #1045  .

In natural events with a multiple data point iceberg event that has a track cluster points, the track and cluster points disappear if you zoom out to the max zoom level and then zoom out once more(using the mouse wheel). This same disappear action happens when zooming in to the 0 zoom level.

- Add conditions based on current projection and zoom levels to prevent removal of track and cluster points

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/natural-events/track.js [hunk 1]
```diff
@@ -48,7 +48,12 @@ export default function naturalEventsTrack (models, ui, config) {
       if (e.key === 'resolution' || e.key === 'rotation') {
         self.trackDetails = (self.trackDetails.id) ? self.removeTrack(map, self.trackDetails) : {};
       } else if (e.key === 'center') {
-        if (self.active) removeOldPoints(map, self.trackDetails.pointArray);
+        // zoom restrictions prevent track/cluster points disappearing on min/max zoom
+        let zoomMax = models.proj.selected.numZoomLevels;
+        let zoom = map.getView().getZoom();
+        if (self.active && zoom < zoomMax && zoom > 0) {
```
Comment (Benjaki2) [inline web/js/natural-events/track.js]: Zoom Max and Min logic should probably be added to `moveend` listener
