### PR TITLE
Fix tour breaking when using manipulating comparison mode b-state

### LINKED ISSUE #1685: Manipulating B-layers causes unwanted side-effects while loading tour steps
**Describe the bug**
While in comparison mode, if the B state layers are maniupulated (removed etc) and then a tour is started or the next tour step is loaded; the layers load the incorrect layers.

**To Reproduce**
1. Start A|B Mode
2. Remove layers from B-side
3. Click Explore Worldview (Tour link)
4. Load a tour
5. Observe incorrect layers loaded

**Expected behavior**
Changing the b-layer state should have no effect on what is loaded in the tour.

### PR DESCRIPTION
**Pull request by ZachTRice**
## Description

Fixes #1685

- If mode has switched to B state by the user, switch back to a state before parsing the tour step.
- Add some validation if there are no layers in the layer list (additional bug breaking in current production)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

### CODE REVIEW

File: web/js/map/ui.js [hunk 1]
```diff
@@ -565,7 +565,8 @@ export function mapui(models, config) {
         id: def.id
       }
     });
-    if (!layer && layers[0].get('group')) {
+
+    if (!layer && layers.length && layers[0].get('group')) {
```
Comment (Benjaki2) [inline web/js/map/ui.js]: Might want a `layers.length > 0` as well to ensure layers[0] exists

Comment (ZachTRice) [reply web/js/map/ui.js]: `layers.length` and `layers.length > 0` are the same. The former being slightly faster.
ref: https://stackoverflow.com/questions/32911424/array-length-vs-array-length-0

Comment (Benjaki2) [reply web/js/map/ui.js]: Whoops. Did not know. 👍

Comment (ZachTRice) [reply web/js/map/ui.js]: All good 😉 let me try rebasing on the new tour story and see if I can reproduce

**Comment by ZachTRice** [comment]
Hey @Benjaki2 I just realized the reason you are seeing an error with the new tour is because I added a fix in Minnie's branch. I just added that fix over in this branch so if you check this PR again with the new tour, you should not see it breaking. 

Really good catch!
